export const APP_SERVICES = [
    {
        id: '18ff56d7-7c1c-4880-a243-12290893cada',
        url: 'product-service-2',
        navigationUrl: '/products/custom-solutions#financial-foundation-mentoring',
        solutionKey: 'financialFoundation',
        outcomeKeys: [
            'roadmap',
            'riskAssessment',
            'assetKnowledge',
            'independentDecision',
            'budgetingMastery',
        ],
    },
    {
        id: '35f103a7-8ca5-4072-89a3-02548c28d5ae',
        url: 'product-service-1',
        navigationUrl: '/products/custom-solutions#portfolio-strategy-tools',
        solutionKey: 'portfolioStrategy',
        outcomeKeys: [
            'framework',
            'rebalancing',
            'toolsProficiency',
            'riskManagement',
            'objectiveDecision',
        ],
    },
    {
        id: '850f6aa6-f2b5-4b89-a303-98660d887ec7',
        url: 'product-service-3',
        navigationUrl: '/products/custom-solutions#algorithmic-trading-solutions',
        solutionKey: 'algoTrading',
        outcomeKeys: [
            'codedSystem',
            'backtestReport',
            'deployedTool',
            'systematicExecution',
            'fullOwnership',
        ],
    },
    {
        id: '91aa5027-325b-4cef-9503-8a03e0790074',
        url: 'product-service-5',
        navigationUrl: '/products/custom-solutions#trading-performance-mentoring',
        solutionKey: 'tradingPerformance',
        outcomeKeys: [
            'performanceView',
            'behavioralPatterns',
            'improvementPlan',
            'selfReviewSkills',
            'tradingDiscipline',
        ],
    },
    {
        id: 'c3d2e0cc-484d-475c-8051-03c70b4e40d6',
        url: 'product-service-4',
        navigationUrl: '/products/custom-solutions#financial-investment-courses',
        solutionKey: 'financialCourse',
        outcomeKeys: [
            'foundationalKnowledge',
            'analysisSkills',
            'toolProficiency',
            'strategicFramework',
            'confidenceToInvest',
        ],
    },
    {
        id: '1f39f7e8-28da-4ef3-b60b-6f662bd4df9d',
        url: undefined,
        navigationUrl: '/products/custom-solutions#personalized-solution',
        solutionKey: 'personalizedSolution',
        outcomeKeys: [
            'tailored',
            'flexible',
            'expert',
            'evolving',
        ],
    },
];
